services:

  postgres:
    image: postgres:16
    container_name: orders-postgres
    environment:
      POSTGRES_DB: orders
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  inventory-mock:
    image: wiremock/wiremock:3.5.4
    container_name: inventory-mock
    ports:
      - "8089:8080"
    volumes:
      - ./wiremock:/home/wiremock
volumes:
  postgres_data: